# Generated by Django 5.1.15 on 2026-05-29 02:50

import django.db.models.deletion
import secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('verified', 'Verified'), ('pool_empty', 'Verified but pool empty')], default='pending', max_length=12)),
                ('verify_token', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('verify_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('single', 'Single choice'), ('multi', 'Multiple choice'), ('likert', 'Likert scale'), ('short_text', 'Short text'), ('image_grid', 'Image grid (single cell)')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('included_in_short', models.BooleanField(default=False, help_text='Include in the 5-question short survey.')),
                ('required', models.BooleanField(default=True)),
                ('likert_min', models.PositiveIntegerField(default=1)),
                ('likert_max', models.PositiveIntegerField(default=5)),
                ('likert_min_label', models.CharField(blank=True, max_length=100)),
                ('likert_max_label', models.CharField(blank=True, max_length=100)),
                ('grid_image', models.ImageField(blank=True, null=True, upload_to='grids/')),
                ('grid_rows', models.PositiveIntegerField(blank=True, null=True)),
                ('grid_cols', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('consent_text', models.TextField(blank=True, help_text='IRB-approved consent language shown before the survey. PLACEHOLDER until the approved wording is pasted in.')),
            ],
        ),
        migrations.CreateModel(
            name='PrizeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('assigned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_code', to='survey.prizeclaim')),
            ],
        ),
        migrations.AddField(
            model_name='prizeclaim',
            name='prize_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='survey.prizecode'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='survey.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.survey'),
        ),
        migrations.CreateModel(
            name='Kiosk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('rotate_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('token_ttl_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('survey', models.ForeignKey(help_text='Survey served when this kiosk is scanned.', on_delete=django.db.models.deletion.PROTECT, related_name='kiosks', to='survey.survey')),
            ],
        ),
        migrations.CreateModel(
            name='SurveySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('length', models.CharField(blank=True, choices=[('short', 'Short (5 questions)'), ('long', 'Long (15 questions)')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=10)),
                ('consented', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('kiosk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='survey.kiosk')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='survey.survey')),
            ],
        ),
        migrations.AddField(
            model_name='prizeclaim',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='survey.surveysession'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True)),
                ('likert_value', models.PositiveIntegerField(blank=True, null=True)),
                ('grid_row', models.PositiveIntegerField(blank=True, null=True)),
                ('grid_col', models.PositiveIntegerField(blank=True, null=True)),
                ('choices', models.ManyToManyField(blank=True, to='survey.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.surveysession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='prizeclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['verified', 'pool_empty'])), fields=('email',), name='one_verified_claim_per_email'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='one_answer_per_question_per_session'),
        ),
    ]
