# Generated by Django 5.1.15 on 2026-07-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='value_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='question',
            name='config_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
